from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^alertas/$', views.alertas_menu, name='alertas_menu'),
    url(r'^alertas/(?P<tipo>[0-2]+)/$', views.tipus, name='tipo'),
    url(r'^setVisto/(?P<id_par>[0-9]+)/$', views.visto, name='visto'),
    url(r'^propuestas/$', views.propuestas_menu, name='propuestas_menu'),
    url(r'^propuestas/add$', views.formPropuesta, name='form_propuesta'),
    url(r'^propuestas/get/(?P<tipo>[1-3]+)/$', views.propuestas_tipo, name='propuestas_tipo'),
    url(r'^propuestas/estado/(?P<id>[0-9]+)/(?P<tipo>[1-3]+)/$', views.setTipoPropuesta, name='propuestas_tipo_propuesta'),
    url(r'^propuestas/(?P<id_par>[0-9]+)/$', views.generarProyecto, name='generarProyecto'),
    url(r'^proyectos/$', views.proyectos_menu, name='proyectos_menu'),
    url(r'^proyectos/(?P<tipo>[0-9]+)/$', views.tipoProyecto, name='tipoProyecto'),
    url(r'^objetivos/$', views.generarOjetivos, name='generarOjetivos'),
    url(r'^objetivos/add$', views.formObjetivo, name='formObjetivo'),
    url(r'^objetivo/eliminar/(?P<id>[0-9]+)/$', views.eliminarObj, name='eliminarObj'),
    url(r'^objetivo/mod/(?P<id>[0-9]+)/$', views.modificarObj, name='modificarObj'),
    url(r'^principios/$', views.generarPrincipios, name='generarPrincipios'),
    url(r'^principio/mod/(?P<id>[0-9]+)/$', views.modificarPrincipio, name='modificarPrincipio'),
    url(r'^principio/eliminar/(?P<id>[0-9]+)/$', views.eliminarPrin, name='eliminarPrin'),
    url(r'^principio/add$', views.formPrincipio, name='formPrincipio'),
    url(r'^proyectos/proyecto/individual/(?P<id>[0-9]+)/$', views.selectProyecto, name='selectProyecto'),
    url(r'^presupuestos/$', views.presupuestos_menu, name='presupuestos_menu'),
    url(r'^evaluaciones/$', views.evaluaciones_menu, name='evaluaciones_menu'),
    url(r'^evaluaciones/evaluacion/(?P<id>[0-9]+)/$', views.selectEvaluacion, name='selectEvaluacion'),
    url(r'^evaluacion/add$', views.formEvaluacion, name='formEvaluacion'),
    url(r'^evaluacion/mod/(?P<id>[0-9]+)/$', views.modificarEvaluacion, name='modificarEvaluacion'),
    url(r'^evaluacion/eliminar/(?P<id>[0-9]+)/$', views.eliminarEvaluacion, name='eliminarEvaluacion'),
    url(r'^evaluacion/add$', views.formMetrica, name='formMetrica'),
    url(r'^metricas/$', views.metricas_menu, name='metricas_menu'),
    url(r'^metrica/add$', views.formMetrica, name='formMetrica'),
    url(r'^metrica/mod/(?P<id>[0-9]+)/$', views.modificarMetrica, name='modificarMetrica'),
    url(r'^metrica/eliminar/(?P<id>[0-9]+)/$', views.eliminarMetrica, name='eliminarMetrica'),
    url(r'^metricas/metrica/(?P<id>[0-9]+)/$', views.selectMetrica, name='selectMetrica'),
    url(r'^metricas/metrica/(?P<id>[0-9]+)/$', views.selectMetricasProjecte, name='selectMetricaProyecto'),
    url(r'^metricas/projecto/(?P<id>[0-9]+)/$', views.selectMetricasProjecte, name='selectMetrica'),
    url(r'^presupuestos/proyectos/$', views.selectPresupostsProjectes, name='selectPresupostsProjectes'),
    url(r'^proyecto/objetivo/(?P<id>[0-9]+)/$', views.selectObjetivoProyecto, name='selectObjetivoProyecto'),
]
