# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=200)),
                ('descripcio', models.CharField(max_length=200)),
                ('data', models.DateTimeField(verbose_name=b'date published')),
                ('llegit', models.IntegerField(default=0)),
                ('prioridad', models.IntegerField(choices=[(1, b'Baja'), (2, b'Media'), (3, b'Alta')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=200)),
                ('nota_real', models.IntegerField(default=0)),
                ('nota_esperada', models.IntegerField(default=0)),
                ('comentari', models.CharField(max_length=500)),
                ('dresponsabilidad', models.CharField(max_length=200)),
                ('nresponsabilidad', models.IntegerField(default=0)),
                ('destrategia', models.CharField(max_length=200)),
                ('nestrategia', models.IntegerField(default=0)),
                ('dadquisicion', models.CharField(max_length=200)),
                ('nadquisicio', models.IntegerField(default=0)),
                ('drendimiento', models.CharField(max_length=200)),
                ('nrendimiento', models.IntegerField(default=0)),
                ('dconformidad', models.CharField(max_length=200)),
                ('nconformidad', models.IntegerField(default=0)),
                ('dconducta', models.CharField(max_length=200)),
                ('nconducta', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficher', models.CharField(max_length=200)),
                ('descripcio', models.CharField(max_length=500)),
                ('tipo', models.IntegerField(choices=[(1, b'Presupost'), (2, b'Dades')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('descripcio', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Principio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=200)),
                ('descripcio', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
                ('data', models.DateTimeField(verbose_name=b'date published')),
                ('presupuesto', models.IntegerField(default=0)),
                ('responsable', models.CharField(max_length=200)),
                ('estado', models.IntegerField(choices=[(1, b'Pendiente'), (2, b'Rechazada'), (3, b'Aplazada'), (4, b'Proyecto')], default=1)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectes.Evaluacion')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectes.Objetivo')),
                ('principio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectes.Principio')),
            ],
        ),
        migrations.AddField(
            model_name='objetivo',
            name='principio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectes.Principio'),
        ),
        migrations.AddField(
            model_name='metrica',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectes.Propuesta'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='metrica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectes.Metrica'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='projecte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectes.Propuesta'),
        ),
    ]
