# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 17:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projectes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrica',
            name='ficher',
        ),
        migrations.AddField(
            model_name='metrica',
            name='dades',
            field=models.CharField(default=datetime.datetime(2016, 5, 1, 17, 57, 32, 738871, tzinfo=utc), max_length=2000),
            preserve_default=False,
        ),
    ]
