# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectes', '0003_metrica_alerta_creada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrica',
            name='dades',
            field=models.CharField(default=0, max_length=2000),
        ),
    ]
